join_event:
  chat_message:
    enabled: true
    message: "[&2+&r] &4%player% &rjoined us !"
  title_message:
    enabled: true
    title: "&4Welcome !"
    subtitle: "&8Welcome &6%player% &8!"
    fadein: 2
    stay: 20
    fadeout: 2

leave_event:
  chat_message:
    enabled: true
    message: "[&2-&r] &4%player% &rleft us !"