# '##::::'##:'########:'####:'##:::::::'####:'########:'####:'########::'######::
# ##:::: ##:... ##..::. ##:: ##:::::::. ##::... ##..::. ##:: ##.....::'##... ##:
# ##:::: ##:::: ##::::: ##:: ##:::::::: ##::::: ##::::: ##:: ##::::::: ##:::..::
# ##:::: ##:::: ##::::: ##:: ##:::::::: ##::::: ##::::: ##:: ######:::. ######::
# ##:::: ##:::: ##::::: ##:: ##:::::::: ##::::: ##::::: ##:: ##...:::::..... ##:
# ##:::: ##:::: ##::::: ##:: ##:::::::: ##::::: ##::::: ##:: ##:::::::'##::: ##:
#. #######::::: ##::::'####: ########:'####:::: ##::::'####: ########:. ######::
#:.......::::::..:::::....::........::....:::::..:::::....::........:::......:::





# --- Placeholders ---
# Place holders can be used anywhere, but if there is no player involved, you can't use the one
# that aren't checked. (Even in commands) Here is the list :

# - %player%         -> Get the player display name                      Player? ✔
# - %player_exact%   -> Get the player exact name                        Player? ✔
# - %x%              -> Get the player X coordinate                      Player? ✔
# - %y%              -> Get the player Y coordinate                      Player? ✔
# - %z%              -> Get the player Z coordinate                      Player? ✔
# - %max_players%    -> Get the maximum of player allowed on the Server  Player? ✖
# - %online_players% -> Get the number of online players                 Player? ✖
# - %server_name%    -> Get the server name                              Player? ✖
# - %server_motd%    -> Get the server motd                              Player? ✖





# --- Config ---
# Here is the Config file to personalize the plugin to fit your own Server !

join_event: # Handling the event when a player join

  chat_message: # The Message in the chat
    enabled: true # Enabled or Not
    message: "[&2+&r] &4%player% &rjoined us !" # Message on itself

  title_message: # A title when the player joins
    enabled: true # Enabled or Not
    title: "&4Welcome !" # Title
    subtitle: "&8Welcome &6%player% &8!" # Subtitle - Action Bar
    fadein: 2 # Fadein of the title
    stay: 5 # Stay of the title
    fadeout: 2 # Fadeout of the title

leave_event: # Handling the event when a player leaves

  chat_message: # The Message in the chat
    enabled: true # Enabled or Not
    message: "[&2-&r] &4%player% &rleft us !" # Message on itself