name: Utilities
version: ${project.version}
main: fr.lygaen.utilities.utilities.Utilities
api-version: 1.13
authors: [Lygaen]
description: A plugin for simple Utilities in Minecraft
commands:
  broadcast:
    description: Broadcast your Message !
    usage: /<command> [message]
    permission: utilities.broadcast
    aliases:
      - bcast
      - bc
  gmc:
    description: Put you in Gamemode Creative (Or the Player targeted)
    usage: /<command> [player=sender]
    permission: utilities.gamemode.creative
  gms:
    description: Put you in Gamemode Survival (Or the Player targeted)
    usage: /<command> [player=sender]
    permission: utilities.gamemode.survival
  gmsp:
    description: Put you in Gamemode Spectator (Or the Player targeted)
    usage: /<command> [player=sender]
    permission: utilities.gamemode.spectator
  gma:
    description: Put you in Gamemode Adventure (Or the Player targeted)
    usage: /<command> [player=sender]
    permission: utilities.gamemode.adventure
  fly:
    description: Make you  allowed to Fly ! (Or the Player targeted)
    usage: /<command> [player=sender]
    permission: utilities.movements.fly
  speed:
    description: Change your speed to [int]
    usage: /<command> [int]
    permission: utilities.movements.speed
  walkspeed:
    description: Change your walk speed to [int]
    usage: /<command> [int]
    permission: utilities.movements.speed.walk
  flyspeed:
    description: Change your fly speed to [int]
    usage: /<command> [player=sender]
    permission: utilities.movements.speed.fly
  vanish:
    description: Vanish you from other Payers
    usage: /<command> [payer=sender]
    permission: utilities.vanish

permissions:

  utilities.vanish:
    description: Allow you to use the /vanish command
    default: op
  utilities.vanish.others:
    description: Allow you to use the /vanish [player] command
    default: op
  utilities.vanish.see:
    description: Allow you to see vanished players
    default: op


  utilities.broadcast:
    description: Allow you to use the /broadcast command
    default: op


  utilities.gamemode:
    utilities.gamemode.creative:
      description: Allow you to use the /gmc command
      default: op
    utilities.gamemode.creative.others:
      description: Allow you to use the /gmc command
      default: op
    utilities.gamemode.survival:
      description: Allow you to use the /gms command
      default: op
    utilities.gamemode.survival.others:
      description: Allow you to use the /gms command
      default: op
    utilities.gamemode.spectator:
      description: Allow you to use the /gmsp command
      default: op
    utilities.gamemode.spectator.others:
      description: Allow you to use the /gms command
      default: op
    utilities.gamemode.adventure:
      description: Allow you to use the /gma command
      default: op
    utilities.gamemode.adventure.others:
      description: Allow you to use the /gma command
      default: op


  utilities.movements:
    utilities.movements.fly:
      description: Allow you to use the /fly command
      default: op
    utilities.movements.fly.others:
      description: Allow you to use the /fly [player] command
      default: op
    utilities.movements.speed:
      description: Allow you to use the /speed command
      default: op
    utilities.movements.speed.others:
      description: Allow you to use the /speed [player] command
      default: op
    utilities.movements.speed.walk:
      description: Allow you to use the /walkspeed command
      default: op
    utilities.movements.speed.walk.others:
      description: Allow you to use the /walkspeed [player] command
      default: op
    utilities.movements.speed.fly:
      description: Allow you to use the /flyspeed command
      default: op
    utilities.movements.speed.fly.others:
      description: Allow you to use the /flyspeed [player] command
      default: op